version: '3'
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - "./../build/keksdose:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/certs:/etc/nginx/certs"